#!/bin/sh

if [ -z "$1" ];then
    echo "usage: $0 dir" >&2
    exit 1
fi

projectdir=$(readlink -f $1)
projectname=$(basename $projectdir)
exportdir=$projectdir/export
date=$(echo $projectname | sed 's/^\([0-9]\+-[0-9]\+-[0-9]\+\)-.*$/\1/')
album="$date"
year=$(echo $date | sed 's/^\([0-9]\+\)-.*$/\1/')
artist=$(echo $projectname | sed 's/^[0-9]\+-[0-9]\+-[0-9]\+-\(.*\)$/\1/')
mp3dir=$exportdir/$artist-$date
mp3dirname=$(basename "$mp3dir")

lame=`which lame`
eyeD3=`which eyeD3`

die() {
    echo $@ >&2
    exit 1
}

check_lame() {
    if [ -z "$lame" ]; then
        die "'lame' is not installed"
    fi
}

check_eyeD3() {
    if [ -z "$eyeD3" ]; then
        die "'eyeD3' is not installed"
    fi
}

check_lame
check_eyeD3


echo exportdir: $exportdir
echo projectname: $projectname
echo date: $date
echo artist: $artist
echo mp3dir: $mp3dir
echo

if [ -z "$projectname" -o -z "$exportdir" -o -z "$date" -o -z "$year" -o -z "$artist" -o -z "$mp3dir" ];then
    die "Bad project directory naming"
fi


cd "$exportdir"
totaltracks=$(ls *.wav | wc -l)
mkdir -p "$mp3dir"
for wav in *.wav;do
    mp3=$(basename "$wav" .wav).mp3
    track=$(echo "$mp3" | sed 's/^\([0-9]\+\)\s\+-.*$/\1/')
    title=$(echo "$mp3" | sed 's/^[0-9]\+\s\+-\s\+\(.*\).mp3$/\1/')

    if [ -z "$mp3" -o -z "$track" -o -z "$title" ];then
        echo "Bad file naming: mp3 '$mp3' track '$track' title '$title'" >&2
        exit 1
    fi

    echo "converting $wav to $mp3: track $track title $title artist $artist year $year album $album"

    $lame \
        -ta "$artist" \
        -tl "$album" \
        -tt "$title" \
        -tn "$track/$totaltracks" \
        -ty "$year" \
        "$wav" "$mp3" || die "Error converting to mp3"

    mv -v "$mp3" "$mp3dir" || die "Error moving file"
done

zipfile="$mp3dirname".zip
zip -r "$zipfile" "$mp3dirname"

echo
echo "archive ready: $(readlink -f $zipfile)"

echo SUCCESS
